### ISSUE TITLE
How to use descriptive text for checkbox?

### ISSUE THREAD

**Issue by ali-kamalizade** [hunzaboy/CSS-Checkbox-Library#7]
First of, I love how easy and stylish the checkboxes look, this is definitely better than the default look.
However, I am struggling to **show text on the right of the checkbox**.
For example, when using _.ckbx-style-13_ then the checkbox is overlapping the actual text.

**Comment by hunzaboy** [comment]
You can use the checkbox inside a div and arrange the layout. Can you share some code so that i can look into it.

**Comment by pszucs** [comment]
Hi @hunzaboy,

Simply adding some text ("Hellooo label text" in the below example) to the label tag results in the following layout issue - I've used your index.html file that it is in the project's root directory:

![css_checkbox_library_label_layout_issue](https://user-images.githubusercontent.com/2471046/52475839-bac2e600-2b94-11e9-801b-9b9c0a93cc1d.png)

Changing the `.ckbx-style-1 label` style to `display: inline` and some `padding-left` seems to solve the issue, however, I'm unable to change the text's font-size because that also changes the checkboxes size.

Any ideas / suggestions?

**Comment by pszucs** [comment]
I've wrapped the text in a `span` tag and added the following styles to it, looks kind of okay now:

```css
.ckbx-style-1 label {display: inline; padding-left: 50px}
.ckbx-style-1 label span {font-size: 13px; position: relative; top: -10px}
```
